name: movie_toz
description: Movie Trailer


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.6.0
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter
  flutterfire_ui: ^0.4.3+4
  get: ^4.6.3
  google_fonts: ^2.3.1
  introduction_screen: ^3.0.2
  lottie: ^1.3.0
  responsive_framework: ^0.2.0
  youtube_player_flutter: ^8.0.0
  google_sign_in: ^5.4.1

dev_dependencies:
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter


flutter_native_splash:
  color: "#000000"
  image: "assets/splash-screen-logo.png"
  android: true
  ios: true


  flutter_lints: ^1.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
